logger:
  log_file: "/tmp/autodrive_local_map"
  log_ext: "log"
  log_lvl: 1

data_folder: "/home/autodrive/Data/final/1_1_3_1/"
calibratios_folder: "/home/autodrive/Developer/autodrive-localmap/src/autodrive_local_map/calibrations/"

map_builder:
  keep_history_sec_length: 10
  max_replayer_rate: 1