image: ros_noetic_image

stages:
  - build
  - test

build_job:

  tags:
    - ros_noetic

  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    - sed -i "s/https:\\/\\//https:\\/\\/gitlab-ci-token:$CI_BUILD_TOKEN@/g" .gitmodules
    - cat .gitmodules
    - git submodule sync --recursive
    - git submodule update --init --recursive

  script:
    - pwd
    - source /opt/ros/noetic/setup.bash
    - cd src/atlas_fusion
    - mkdir build && cd build
    - cmake ..
    - make -j4

  artifacts:
    paths:
      - src/atlas_fusion/build/

test_job:

  tags:
    - ros_noetic

  stage: test

  dependencies:
    - build_job

  script:
    - cd src/atlas_fusion/build/
    - make test
