logger:
  log_file: "/tmp/atlas_fusion"
  log_ext: "log"
  log_lvl: 1

#data_folder: "/home/default_user/Data/final/test/2_1_3_1/"
data_folder: "/home/default_user/Data/rec_1_part_1/"
calibratios_folder: "/home/default_user/Developer/Atlas-Fusion/src/atlas_fusion/calibrations/"

map_builder:
  keep_history_sec_length: 10
  max_replayer_rate: 10

laser_aggregator:
  lasers: 32
  points_per_laser: 50000

lidar_aggregator:
  leaf_size: 0.2
  global_leaf_size: 1.0
  no_of_batches_per_scan: 100
  aggretation_time: 1.0

self_model:
  kalman_process_noise: 1.0
  kalman_observation_noise: 0.1

lidar_img_plotter:
  max_distance: 50

pose_logger:
  gnss: 100
  imu: 1000

laser_segmenter:
  vectorizer_sigma: 0.02
  segmenter_step: 10
  segmenter_lower_bound: 0.002
  segmenter_upper_bound: 0.2
  segmenter_scaling: 0.01